# SPDX-FileCopyrightText: René Widera
#
# SPDX-License-Identifier: ISC
"""``computeMCP-handshake``: request gateway access from inside a Terok container.

This is the counterpart to the gateway's enrollment endpoint.  It runs where the
*agent* runs (inside a Terok task), asks the gateway for access, waits for an
operator to approve the request on the gateway console, and, on approval,
receives this project's token.  It then records the token either in an env file
sourced by ``~/.bashrc`` or directly in ``~/.bashrc``, and prints the MCP
``environment`` snippet.

It carries no SSH credentials and never learns any target's route.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import sys
from pathlib import Path

import aiohttp

DEFAULT_HOST = "host.containers.internal"
DEFAULT_PORT = 2222
POLL_INTERVAL = 3.0
BEGIN_MARK = "# >>> computeMCP >>"
END_MARK = "# <<< computeMCP <<"


class HandshakeError(RuntimeError):
    pass


def _build_gateway_url(args: argparse.Namespace) -> str:
    if args.gateway:
        return args.gateway.rstrip("/")
    env = os.environ.get("COMPUTEMCP_GATEWAY")
    if env:
        return env.rstrip("/")
    return f"http://{args.host}:{args.port}"


def _parse_system(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.replace(" ", "").split(",") if item.strip()]


async def _request_enrollment(
    base: str, client_id: str, targets: list[str], label: str | None, timeout: float
) -> dict:
    payload = {"client_id": client_id, "targets": targets}
    if label:
        payload["label"] = label
    try:
        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{base}/v1/enroll",
                json=payload,
                timeout=aiohttp.ClientTimeout(total=timeout),
            ) as response:
                body = await response.text()
                if response.status >= 400:
                    raise HandshakeError(
                        f"gateway rejected the request ({response.status}): "
                        f"{body[:300]}"
                    )
                return json.loads(body)
    except aiohttp.ClientError as exc:
        raise HandshakeError(f"cannot reach gateway at {base}: {exc}") from exc


async def _poll(
    base: str, request_id: str, secret: str, timeout: float, interval: float
) -> dict:
    deadline = asyncio.get_event_loop().time() + timeout
    headers = {"X-Enroll-Secret": secret}
    while True:
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    f"{base}/v1/enroll/{request_id}",
                    headers=headers,
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as response:
                    body = await response.text()
                    if response.status == 404:
                        raise HandshakeError("the request is no longer known")
                    if response.status >= 400:
                        raise HandshakeError(
                            f"gateway poll failed ({response.status}): {body[:200]}"
                        )
                    data = json.loads(body)
        except aiohttp.ClientError:
            # Transient network hiccup while waiting; keep polling.
            data = {"status": "pending"}
        status = data.get("status")
        if status != "pending":
            return data
        if asyncio.get_event_loop().time() >= deadline:
            raise HandshakeError("timed out waiting for approval")
        print(".", end="", flush=True)
        await asyncio.sleep(interval)


def _render_env_file(url: str, token: str) -> str:
    return (
        f"# Generated by computeMCP-handshake; secret - do not commit.\n"
        f"export COMPUTEMCP_GATEWAY={json.dumps(url)}\n"
        f"export COMPUTEMCP_TOKEN={json.dumps(token)}\n"
    )


def _update_bashrc(bashrc: Path, *, source_file: Path | None, url: str, token: str) -> None:
    """Idempotently write the exports (or a source line) between markers."""
    if source_file is not None:
        body = f'[ -r "{source_file}" ] && . "{source_file}"'
    else:
        body = (
            f"export COMPUTEMCP_GATEWAY={json.dumps(url)}\n"
            f"export COMPUTEMCP_TOKEN={json.dumps(token)}"
        )
    block = f"{BEGIN_MARK}\n{body}\n{END_MARK}"
    text = bashrc.read_text() if bashrc.exists() else ""
    pattern = re.compile(
        re.escape(BEGIN_MARK) + r".*?" + re.escape(END_MARK), re.DOTALL
    )
    if pattern.search(text):
        text = pattern.sub(block, text)
    else:
        if text and not text.endswith("\n"):
            text += "\n"
        text += block + "\n"
    bashrc.write_text(text)


def _mcp_snippet(url: str, token: str) -> str:
    return (
        '  "compute": {\n'
        '    "type": "local",\n'
        '    "command": ["/home/dev/.local/bin/computeMCP-mcp"],\n'
        '    "enabled": true,\n'
        '    "environment": {\n'
        f'      "COMPUTEMCP_GATEWAY": {json.dumps(url)},\n'
        f'      "COMPUTEMCP_TOKEN": {json.dumps(token)}\n'
        "    }\n"
        "  }"
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="computeMCP-handshake",
        description="Request gateway access from inside a Terok container.",
    )
    parser.add_argument("client_id", help="project/client id to enroll, e.g. picongpu-bot-dev2")
    parser.add_argument("--gateway", help="gateway base URL (overrides env/host/port)")
    parser.add_argument("--host", default=DEFAULT_HOST, help=f"gateway host (default: {DEFAULT_HOST})")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help=f"gateway port (default: {DEFAULT_PORT})")
    parser.add_argument(
        "--system",
        help="comma-separated target allow-list, e.g. 'hal,fwk394'; "
        "omit for an empty ACL (* = all targets)",
    )
    parser.add_argument("--label", help="human-readable label for this client")
    parser.add_argument(
        "--bashrc",
        type=Path,
        default=Path.home() / ".bashrc",
        help="shell file to update (default: ~/.bashrc)",
    )
    parser.add_argument(
        "--env-file",
        type=Path,
        default=None,
        help="write exports to this file and source it from --bashrc "
        "(keeps the token out of ~/.bashrc)",
    )
    parser.add_argument("--no-write", action="store_true", help="do not touch any file; print the snippet only")
    parser.add_argument("--timeout", type=float, default=900.0, help="seconds to wait for approval (default: 900)")
    parser.add_argument("--poll-interval", type=float, default=POLL_INTERVAL)
    parser.add_argument("--json", action="store_true", help="machine-readable result on stdout")
    return parser


async def _run(args: argparse.Namespace) -> int:
    base = _build_gateway_url(args)
    targets = _parse_system(args.system)

    print(f"Requesting access to {base} as client {args.client_id!r}")
    print(f"targets: {', '.join(targets) or '(empty - no systems)'}")
    created = await _request_enrollment(base, args.client_id, targets, args.label, 30.0)
    request_id = created["request_id"]
    secret = created["poll_secret"]
    print(
        f"\nRequest queued: {request_id}\n"
        "Approve it on the gateway operator console:\n"
        f"    gateway> enrollments\n"
        f"    gateway> approve {request_id}\n"
        "\nWaiting for approval ",
        end="",
        flush=True,
    )
    result = await _poll(base, request_id, secret, args.timeout, args.poll_interval)

    status = result.get("status")
    if status == "denied":
        print("\nrequest denied by the operator.")
        return 2
    if status != "approved":
        print(f"\nunexpected status: {status}")
        return 1

    token = result.get("token")
    if not token:
        print("\napproval returned no token (already collected?).")
        return 1
    client_id = result.get("client_id", args.client_id)
    print(f"\nApproved. Token for client {client_id!r} received.")

    source_file = None
    if not args.no_write:
        if args.env_file is not None:
            source_file = args.env_file
            source_file.parent.mkdir(parents=True, exist_ok=True)
            source_file.write_text(_render_env_file(base, token))
            try:
                source_file.chmod(0o600)
            except OSError:
                pass
        _update_bashrc(args.bashrc, source_file=source_file, url=base, token=token)
        print(f"Updated {args.bashrc}" + (f" (sourcing {source_file})" if source_file else ""))

    if args.json:
        print(json.dumps({"status": "approved", "client_id": client_id,
                          "gateway": base, "token": token}))
    else:
        print(
            "\nThe running opencode will NOT see this until restarted. To wire it "
            "into the MCP entry directly, add under \"mcp\":\n"
        )
        print(_mcp_snippet(base, token))
    return 0


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return asyncio.run(_run(args))
    except HandshakeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\naborted", file=sys.stderr)
        return 130


if __name__ == "__main__":
    raise SystemExit(main())
